server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: odilhon1985
    url: jdbc:postgresql://localhost:5432/files
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
upload:
  server:
    folder: C:/Users/Java/Pictures/sbfs